[{"test_case": "test_case_00036_00000", "type": "error", "result_detail": "relation \"cte1\" does not exist\nLINE 9: with cte3 as (select ref2.j as i from cte1 as ref2), cte1 as...\n                                              ^\nDETAIL:  There is a WITH item named \"cte1\", but it cannot be referenced from this part of the query.\nHINT:  Use WITH RECURSIVE, or re-order the WITH items to remove forward references.\n", "error_stage": "set_up"}]